"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "matches",
      [
        {
          id: 1,
          homeTeamId: 193,
          homeTeamName: "PEC Zwolle",
          homeTeamLogo: "https://media.api-sports.io/football/teams/193.png",
          goalsHomeTeam: 1,
          awayTeamId: 195,
          awayTeamName: "Willem II",
          awayTeamLogo: "https://media.api-sports.io/football/teams/195.png",
          goalsAwayTeam: 3,
          eventTimeStamp: 1593882000,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          homeTeamId: 208,
          homeTeamName: "Emmen",
          homeTeamLogo: "https://media.api-sports.io/football/teams/208.png",
          goalsHomeTeam: 0,
          awayTeamId: 202,
          awayTeamName: "Groningen",
          awayTeamLogo: "https://media.api-sports.io/football/teams/202.png",
          goalsAwayTeam: 1,
          eventTimeStamp: 1593882000,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          homeTeamId: 200,
          homeTeamName: "Vitesse",
          homeTeamLogo: "https://media.api-sports.io/football/teams/200.png",
          goalsHomeTeam: 2,
          awayTeamId: 194,
          awayTeamName: "Ajax",
          awayTeamLogo: "https://media.api-sports.io/football/teams/194.png",
          goalsAwayTeam: 2,
          eventTimeStamp: 1593882000,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          homeTeamId: 204,
          homeTeamName: "VVV Venlo",
          homeTeamLogo: "https://media.api-sports.io/football/teams/204.png",
          goalsHomeTeam: 3,
          awayTeamId: 417,
          awayTeamName: "Waalwijk",
          awayTeamLogo: "https://media.api-sports.io/football/teams/417.png",
          goalsAwayTeam: 1,
          eventTimeStamp: 1593862200,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          homeTeamId: 415,
          homeTeamName: "Twente",
          homeTeamLogo: "https://media.api-sports.io/football/teams/415.png",
          goalsHomeTeam: 1,
          awayTeamId: 197,
          awayTeamName: "PSV Eindhoven",
          awayTeamLogo: "https://media.api-sports.io/football/teams/197.png",
          goalsAwayTeam: 1,
          eventTimeStamp: 1593862200,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          homeTeamId: 206,
          homeTeamName: "Heracles",
          homeTeamLogo: "https://media.api-sports.io/football/teams/206.png",
          goalsHomeTeam: 0,
          awayTeamId: 210,
          awayTeamName: "Heerenveen",
          awayTeamLogo: "https://media.api-sports.io/football/teams/210.png",
          goalsAwayTeam: 4,
          eventTimeStamp: 1593862200,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          homeTeamId: 209,
          homeTeamName: "Feyenoord",
          homeTeamLogo: "https://media.api-sports.io/football/teams/209.png",
          goalsHomeTeam: 2,
          awayTeamId: 426,
          awayTeamName: "Sparta Rotterdam",
          awayTeamLogo: "https://media.api-sports.io/football/teams/426.png",
          goalsAwayTeam: 2,
          eventTimeStamp: 1593948600,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          homeTeamId: 198,
          homeTeamName: "ADO Den Haag",
          homeTeamLogo: "https://media.api-sports.io/football/teams/198.png",
          goalsHomeTeam: 2,
          awayTeamId: 207,
          awayTeamName: "Utrecht",
          awayTeamLogo: "https://media.api-sports.io/football/teams/207.png",
          goalsAwayTeam: 4,
          eventTimeStamp: 1593948600,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          homeTeamId: 201,
          homeTeamName: "AZ Alkmaar",
          homeTeamLogo: "https://media.api-sports.io/football/teams/201.png",
          goalsHomeTeam: 4,
          awayTeamId: 205,
          awayTeamName: "Fortuna Sittard",
          awayTeamLogo: "https://media.api-sports.io/football/teams/205.png",
          goalsAwayTeam: 0,
          eventTimeStamp: 1593948600,
          round: "Demo Round 1",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          homeTeamId: 193,
          homeTeamName: "PEC Zwolle",
          homeTeamLogo: "https://media.api-sports.io/football/teams/193.png",
          goalsHomeTeam: 1,
          awayTeamId: 195,
          awayTeamName: "Willem II",
          awayTeamLogo: "https://media.api-sports.io/football/teams/195.png",
          goalsAwayTeam: 1,
          eventTimeStamp: 1594486800,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          homeTeamId: 208,
          homeTeamName: "Emmen",
          homeTeamLogo: "https://media.api-sports.io/football/teams/208.png",
          goalsHomeTeam: 2,
          awayTeamId: 202,
          awayTeamName: "Groningen",
          awayTeamLogo: "https://media.api-sports.io/football/teams/202.png",
          goalsAwayTeam: 1,
          eventTimeStamp: 1594486800,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          homeTeamId: 200,
          homeTeamName: "Vitesse",
          homeTeamLogo: "https://media.api-sports.io/football/teams/200.png",
          goalsHomeTeam: 0,
          awayTeamId: 194,
          awayTeamName: "Ajax",
          awayTeamLogo: "https://media.api-sports.io/football/teams/194.png",
          goalsAwayTeam: 0,
          eventTimeStamp: 1594486800,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          homeTeamId: 204,
          homeTeamName: "VVV Venlo",
          homeTeamLogo: "https://media.api-sports.io/football/teams/204.png",
          goalsHomeTeam: 3,
          awayTeamId: 417,
          awayTeamName: "Waalwijk",
          awayTeamLogo: "https://media.api-sports.io/football/teams/417.png",
          goalsAwayTeam: 2,
          eventTimeStamp: 1594553400,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          homeTeamId: 415,
          homeTeamName: "Twente",
          homeTeamLogo: "https://media.api-sports.io/football/teams/415.png",
          goalsHomeTeam: 1,
          awayTeamId: 197,
          awayTeamName: "PSV Eindhoven",
          awayTeamLogo: "https://media.api-sports.io/football/teams/197.png",
          goalsAwayTeam: 4,
          eventTimeStamp: 1594553400,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          homeTeamId: 206,
          homeTeamName: "Heracles",
          homeTeamLogo: "https://media.api-sports.io/football/teams/206.png",
          goalsHomeTeam: 0,
          awayTeamId: 210,
          awayTeamName: "Heerenveen",
          awayTeamLogo: "https://media.api-sports.io/football/teams/210.png",
          goalsAwayTeam: 2,
          eventTimeStamp: 1594553400,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 16,
          homeTeamId: 209,
          homeTeamName: "Feyenoord",
          homeTeamLogo: "https://media.api-sports.io/football/teams/209.png",
          goalsHomeTeam: 2,
          awayTeamId: 426,
          awayTeamName: "Sparta Rotterdam",
          awayTeamLogo: "https://media.api-sports.io/football/teams/426.png",
          goalsAwayTeam: 0,
          eventTimeStamp: 1594486800,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          homeTeamId: 198,
          homeTeamName: "ADO Den Haag",
          homeTeamLogo: "https://media.api-sports.io/football/teams/198.png",
          goalsHomeTeam: 1,
          awayTeamId: 207,
          awayTeamName: "Utrecht",
          awayTeamLogo: "https://media.api-sports.io/football/teams/207.png",
          goalsAwayTeam: 2,
          eventTimeStamp: 1594486800,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          homeTeamId: 201,
          homeTeamName: "AZ Alkmaar",
          homeTeamLogo: "https://media.api-sports.io/football/teams/201.png",
          goalsHomeTeam: 1,
          awayTeamId: 205,
          awayTeamName: "Fortuna Sittard",
          awayTeamLogo: "https://media.api-sports.io/football/teams/205.png",
          goalsAwayTeam: 0,
          eventTimeStamp: 1594486800,
          round: "Demo Round 2",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          homeTeamId: 193,
          homeTeamName: "PEC Zwolle",
          homeTeamLogo: "https://media.api-sports.io/football/teams/193.png",
          goalsHomeTeam: null,
          awayTeamId: 195,
          awayTeamName: "Willem II",
          awayTeamLogo: "https://media.api-sports.io/football/teams/195.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595048400,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          homeTeamId: 208,
          homeTeamName: "Emmen",
          homeTeamLogo: "https://media.api-sports.io/football/teams/208.png",
          goalsHomeTeam: null,
          awayTeamId: 202,
          awayTeamName: "Groningen",
          awayTeamLogo: "https://media.api-sports.io/football/teams/202.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595048400,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 21,
          homeTeamId: 200,
          homeTeamName: "Vitesse",
          homeTeamLogo: "https://media.api-sports.io/football/teams/200.png",
          goalsHomeTeam: null,
          awayTeamId: 194,
          awayTeamName: "Ajax",
          awayTeamLogo: "https://media.api-sports.io/football/teams/194.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595048400,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 22,
          homeTeamId: 204,
          homeTeamName: "VVV Venlo",
          homeTeamLogo: "https://media.api-sports.io/football/teams/204.png",
          goalsHomeTeam: null,
          awayTeamId: 417,
          awayTeamName: "Waalwijk",
          awayTeamLogo: "https://media.api-sports.io/football/teams/417.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595158200,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 23,
          homeTeamId: 415,
          homeTeamName: "Twente",
          homeTeamLogo: "https://media.api-sports.io/football/teams/415.png",
          goalsHomeTeam: null,
          awayTeamId: 197,
          awayTeamName: "PSV Eindhoven",
          awayTeamLogo: "https://media.api-sports.io/football/teams/197.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595158200,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 24,
          homeTeamId: 206,
          homeTeamName: "Heracles",
          homeTeamLogo: "https://media.api-sports.io/football/teams/206.png",
          goalsHomeTeam: null,
          awayTeamId: 210,
          awayTeamName: "Heerenveen",
          awayTeamLogo: "https://media.api-sports.io/football/teams/210.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595158200,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 25,
          homeTeamId: 209,
          homeTeamName: "Feyenoord",
          homeTeamLogo: "https://media.api-sports.io/football/teams/209.png",
          goalsHomeTeam: null,
          awayTeamId: 426,
          awayTeamName: "Sparta Rotterdam",
          awayTeamLogo: "https://media.api-sports.io/football/teams/426.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595091600,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 26,
          homeTeamId: 198,
          homeTeamName: "ADO Den Haag",
          homeTeamLogo: "https://media.api-sports.io/football/teams/198.png",
          goalsHomeTeam: null,
          awayTeamId: 207,
          awayTeamName: "Utrecht",
          awayTeamLogo: "https://media.api-sports.io/football/teams/207.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595091600,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 27,
          homeTeamId: 201,
          homeTeamName: "AZ Alkmaar",
          homeTeamLogo: "https://media.api-sports.io/football/teams/201.png",
          goalsHomeTeam: null,
          awayTeamId: 205,
          awayTeamName: "Fortuna Sittard",
          awayTeamLogo: "https://media.api-sports.io/football/teams/205.png",
          goalsAwayTeam: null,
          eventTimeStamp: 1595091600,
          round: "Demo Round 3",
          status: "FT",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("matches", null, {});
  },
};
